import { Trip } from './types';

export const createEmptyTrip = (custom?: Partial<Trip>): Trip => {
  const tripId = custom?.id || `trip-${Date.now().toString(36)}`;
  const randomCode = `VIAJE-${Math.floor(1000 + Math.random() * 9000)}`;

  return {
    id: tripId,
    title: custom?.title || 'Nuestro Viaje Soñado',
    subtitle: custom?.subtitle || 'Una aventura inolvidable para dos',
    coverImage:
      custom?.coverImage ||
      'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1600&q=80',
    startDate: custom?.startDate || new Date().toISOString().split('T')[0],
    endDate:
      custom?.endDate ||
      new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    currency: custom?.currency || 'EUR',
    partners: custom?.partners || [
      {
        id: 'p1',
        name: 'Viajero 1',
        avatarEmoji: '🧔',
        avatarColor: '#5A5A40',
        nickname: 'Amor',
      },
      {
        id: 'p2',
        name: 'Viajero 2',
        avatarEmoji: '🌸',
        avatarColor: '#D4A373',
        nickname: 'Cariño',
      },
    ],
    currentActivePartnerId: 'p1',
    inviteCode: custom?.inviteCode || randomCode,
    createdAt: new Date().toISOString(),
    lastSyncedAt: new Date().toISOString(),
    expenses: custom?.expenses || [],
    settlements: custom?.settlements || [],
    cities: custom?.cities || [],
    transports: custom?.transports || [],
    accommodations: custom?.accommodations || [],
    sites: custom?.sites || [],
    packingList: custom?.packingList || [],
    documents: custom?.documents || [],
    tasks: custom?.tasks || [],
    messages: custom?.messages || [],
    gallery: custom?.gallery || [],
    notifications: custom?.notifications || [],
  };
};

export const demoTripTemplate: Trip = {
  id: 'trip-roma-amalfi-2026',
  title: 'Nuestra Luna de Miel & Ruta Italiana',
  subtitle: 'Roma, Florencia, Siena y la mágica Costa Amalfitana',
  coverImage: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=1600&q=80',
  startDate: '2026-10-15',
  endDate: '2026-10-28',
  currency: 'EUR',
  partners: [
    {
      id: 'p1',
      name: 'Lucas',
      avatarEmoji: '✈️',
      avatarColor: '#5A5A40',
      nickname: 'Luqui',
    },
    {
      id: 'p2',
      name: 'Sofía',
      avatarEmoji: '🌸',
      avatarColor: '#D4A373',
      nickname: 'Sofi',
    },
  ],
  currentActivePartnerId: 'p1',
  inviteCode: 'AMORE-2026',
  createdAt: new Date().toISOString(),
  lastSyncedAt: new Date().toISOString(),
  expenses: [
    {
      id: 'exp-1',
      tripId: 'trip-roma-amalfi-2026',
      description: 'Vuelos Internacionales Madrid - Roma (Ida y Vuelta)',
      amount: 480,
      currency: 'EUR',
      category: 'vuelos',
      date: '2026-08-10',
      paidById: 'p1',
      splitType: 'equal',
      splitRatio: { p1: 50, p2: 50 },
      status: 'pagado',
      notes: 'Iberia Express con equipaje de bodega incluido para ambos',
      createdAt: '2026-08-10T10:00:00.000Z',
    },
    {
      id: 'exp-2',
      tripId: 'trip-roma-amalfi-2026',
      description: 'Hotel Boutique Trastevere Roma (4 noches)',
      amount: 620,
      currency: 'EUR',
      category: 'alojamiento',
      date: '2026-08-15',
      paidById: 'p2',
      splitType: 'equal',
      splitRatio: { p1: 50, p2: 50 },
      status: 'pagado',
      notes: 'Incluye desayuno en la terraza y vista al jardín',
      createdAt: '2026-08-15T14:30:00.000Z',
    },
    {
      id: 'exp-3',
      tripId: 'trip-roma-amalfi-2026',
      description: 'Entradas sin cola Coliseo, Foro y Palatino + Tour subterráneo',
      amount: 110,
      currency: 'EUR',
      category: 'actividades',
      date: '2026-08-20',
      paidById: 'p1',
      splitType: 'equal',
      splitRatio: { p1: 50, p2: 50 },
      status: 'pagado',
      notes: 'Pase oficial con guía en español a las 10:30hs',
      createdAt: '2026-08-20T16:00:00.000Z',
    },
    {
      id: 'exp-4',
      tripId: 'trip-roma-amalfi-2026',
      description: 'Alquiler Fiat 500 Cabriolet en Florencia (4 días)',
      amount: 320,
      currency: 'EUR',
      category: 'transporte',
      date: '2026-08-25',
      paidById: 'p2',
      splitType: 'equal',
      splitRatio: { p1: 50, p2: 50 },
      status: 'reservado',
      notes: 'Se abona al retirar en la estación Santa Maria Novella',
      createdAt: '2026-08-25T11:20:00.000Z',
    },
    {
      id: 'exp-5',
      tripId: 'trip-roma-amalfi-2026',
      description: 'Cena Romántica de Aniversario en Positano (Rada Restaurant)',
      amount: 220,
      currency: 'EUR',
      category: 'comida',
      date: '2026-08-28',
      paidById: 'p1',
      splitType: 'p1_only',
      splitRatio: { p1: 100, p2: 0 },
      status: 'pendiente',
      notes: 'Regalo sorpresa de Lucas para Sofía frente al mar',
      createdAt: '2026-08-28T19:00:00.000Z',
    },
    {
      id: 'exp-6',
      tripId: 'trip-roma-amalfi-2026',
      description: 'Tren de Alta Velocidad Frecciarossa Roma -> Florencia',
      amount: 98,
      currency: 'EUR',
      category: 'transporte',
      date: '2026-08-22',
      paidById: 'p1',
      splitType: 'equal',
      splitRatio: { p1: 50, p2: 50 },
      status: 'pagado',
      notes: 'Asientos juntos con mesa en clase Premium',
      createdAt: '2026-08-22T09:15:00.000Z',
    },
  ],
  settlements: [],
  cities: [
    {
      id: 'city-roma',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Roma',
      country: 'Italia',
      arrivalDate: '2026-10-15',
      departureDate: '2026-10-19',
      coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1000&q=80',
      order: 1,
      emergencyInfo: {
        police: '112 (Emergencias generales) / 113 (Polizia di Stato)',
        medical: '118 (Ambulancia)',
        embassy: 'Consulado General: +39 06 4807 0300 (Via Po 24)',
      },
      practicalTips: {
        weather: 'Otoño suave (18°C a 23°C), llevar chaqueta liviana para las noches',
        plugs: 'Tipo C y F (230V / 50Hz) - clavijas europeas estándar',
        transport: 'Metro líneas A y B, o pase diario de autobús ATAC (7€). Centro ideal para caminar',
        localCurrency: 'Euro (€) - Aceptan tarjeta contactless en casi todos lados',
        safety: 'Cuidar pertenencias en metro Termini y Fontana di Trevi',
        bestTime: 'Temprano por la mañana (7:30 - 9:00) para fotos sin gente en Trevi',
      },
      dayPlans: [
        {
          id: 'plan-roma-d1',
          date: '2026-10-15',
          dayNumber: 1,
          title: 'Llegada, Check-in en Trastevere y Paseo al Atardecer',
          morningActivities: ['Llegada a Fiumicino 10:45hs', 'Traslado en Leonardo Express a Termini'],
          afternoonActivities: ['Check-in en Hotel Boutique Trastevere', 'Almuerzo: Tonnarello (Cacio e Pepe)', 'Caminar por el Puente Sisto'],
          eveningActivities: ['Mirador del Gianicolo para ver toda Roma iluminada', 'Gelato artesanal en Frigidarium'],
          notes: 'Día relajado para acomodarnos al horario',
        },
        {
          id: 'plan-roma-d2',
          date: '2026-10-16',
          dayNumber: 2,
          title: 'Roma Imperial: Coliseo, Foros y Panteón',
          morningActivities: ['09:30 Café y cornetto en Sant’Eustachio', '10:30 Tour Guiado Coliseo y Foro Romano'],
          afternoonActivities: ['Panteón de Agripa', 'Plaza Navona y Fuentes de Bernini'],
          eveningActivities: ['Cena en Osteria da Fortunata (pasta fresca hecha a mano)', 'Trevi de noche'],
          notes: 'Llevar calzado muy cómodo para adoquines',
        },
        {
          id: 'plan-roma-d3',
          date: '2026-10-17',
          dayNumber: 3,
          title: 'Vaticano, Capilla Sixtina y Castillo Sant’Angelo',
          morningActivities: ['Museos Vaticanos y Capilla Sixtina (Tickets 09:00hs)', 'Basílica de San Pedro'],
          afternoonActivities: ['Paseo por Borgo Pio', 'Castel Sant’Angelo al atardecer'],
          eveningActivities: ['Cena romántica en Trastevere', 'Tragos en Freni e Frizioni'],
          notes: 'Código de vestimenta para el Vaticano: hombros y rodillas cubiertos',
        },
      ],
    },
    {
      id: 'city-florencia',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Florencia & Toscana',
      country: 'Italia',
      arrivalDate: '2026-10-19',
      departureDate: '2026-10-23',
      coverImage: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=1000&q=80',
      order: 2,
      emergencyInfo: {
        police: '112 / Polizia Municipale: +39 055 32831',
        medical: '118 (Hospital Santa Maria Nuova)',
        embassy: 'Consulado honorario: +39 055 284197',
      },
      practicalTips: {
        weather: 'Templado con brisas frescas (16°C a 21°C)',
        plugs: 'Tipo C / F (230V)',
        transport: 'Totalmente peatonal, auto solo para recorrer los viñedos del Chianti',
        localCurrency: 'Euro (€)',
        safety: 'Ciudad muy segura, prestar atención en Ponte Vecchio',
        bestTime: 'Atardecer inolvidable desde Piazzale Michelangelo',
      },
      dayPlans: [
        {
          id: 'plan-flo-d1',
          date: '2026-10-19',
          dayNumber: 4,
          title: 'Llegada en Tren Bala, Duomo y Ponte Vecchio',
          morningActivities: ['Frecciarossa 10:15 desde Roma', 'Check-in cerca de Piazza della Signoria'],
          afternoonActivities: ['Catedral Santa Maria del Fiore y Cúpula de Brunelleschi', 'Galería Uffizi'],
          eveningActivities: ['Puesta de sol con vino en Piazzale Michelangelo'],
          notes: 'Subir los 463 escalones de la cúpula con calma',
        },
        {
          id: 'plan-flo-d2',
          date: '2026-10-20',
          dayNumber: 5,
          title: 'Ruta en Fiat 500 por Chianti & San Gimignano',
          morningActivities: ['Retirar Fiat 500 Cabrio', 'Paseo panorámico por viñedos de Greve in Chianti'],
          afternoonActivities: ['Degustación de vinos y tabla toscana en Antinori', 'Caminar por torres de San Gimignano'],
          eveningActivities: ['Regreso y cena de Bistecca alla Fiorentina'],
          notes: 'Manejar de día para disfrutar de los cipreses',
        },
      ],
    },
    {
      id: 'city-costa-amalfitana',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Positano & Costa Amalfitana',
      country: 'Italia',
      arrivalDate: '2026-10-23',
      departureDate: '2026-10-28',
      coverImage: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=80',
      order: 3,
      emergencyInfo: {
        police: '112 / Carabinieri Positano: +39 089 875011',
        medical: '118 / Guardia Medica Sorrento: +39 081 5331111',
        embassy: 'Emergencias Nápoles: +39 081 761 4303',
      },
      practicalTips: {
        weather: 'Clima mediterráneo soleado (22°C a 25°C), ideal para navegar',
        plugs: 'Tipo C / F (230V)',
        transport: 'Ferries marítimos (Travelmar) para evitar el tráfico de la cornisa',
        localCurrency: 'Euro (€)',
        safety: 'Precaución en escalinatas empinadas y senderos rocosos',
        bestTime: 'Navegación al mediodía con parada en Gruta Esmeralda',
      },
      dayPlans: [
        {
          id: 'plan-ama-d1',
          date: '2026-10-23',
          dayNumber: 8,
          title: 'Llegada al Paraíso, Vista al Mar y Limoncello',
          morningActivities: ['Tren a Nápoles y ferry a Positano', 'Llegada al Hotel frente al acantilado'],
          afternoonActivities: ['Bajar a Spiaggia Grande', 'Comprar sandalias artesanales a medida'],
          eveningActivities: ['Cena en terraza con vista a las luces de Positano', 'Brindis con limoncello casero'],
          notes: 'Contratar servicio de maletero para las escaleras',
        },
      ],
    },
  ],
  transports: [
    {
      id: 'trans-1',
      tripId: 'trip-roma-amalfi-2026',
      type: 'vuelo',
      title: 'Vuelo de Ida Madrid (MAD) -> Roma Fiumicino (FCO)',
      operator: 'Iberia Express (IB3214)',
      bookingReference: 'IB-994KLA',
      departurePlace: 'Madrid Barajas T4',
      arrivalPlace: 'Roma Fiumicino T3',
      departureDateTime: '2026-10-15T08:30:00',
      arrivalDateTime: '2026-10-15T11:05:00',
      flightNumber: 'IB 3214',
      terminal: 'T4 (Madrid) / T3 (Roma)',
      gate: 'K72 (A confirmar en aeropuerto)',
      seatPartner1: '14A (Ventana)',
      seatPartner2: '14B (Medio)',
      baggageNotes: '2 x Maleta en bodega 23kg + 2 carry on 10kg',
      notes: 'Check-in online abre 24hs antes. Llevar pasaportes a mano',
      status: 'confirmado',
      directLinkOrTicket: 'https://www.iberia.com/es/gestion-de-reservas/',
    },
    {
      id: 'trans-2',
      tripId: 'trip-roma-amalfi-2026',
      type: 'tren',
      title: 'Tren Alta Velocidad Roma Termini -> Florencia Santa Maria Novella',
      operator: 'Trenitalia - Frecciarossa 9520',
      bookingReference: 'PNR-FRECCIA8812',
      departurePlace: 'Roma Termini (Vía 6)',
      arrivalPlace: 'Firenze SMN',
      departureDateTime: '2026-10-19T10:15:00',
      arrivalDateTime: '2026-10-19T11:47:00',
      terminal: 'Estación Central Termini',
      seatPartner1: 'Coche 3, Asiento 21',
      seatPartner2: 'Coche 3, Asiento 22',
      baggageNotes: 'Equipaje ilimitado en compartimento superior',
      notes: 'Llegar 15 minutos antes. WiFi y café de cortesía a bordo',
      status: 'confirmado',
      directLinkOrTicket: 'https://www.trenitalia.com',
    },
    {
      id: 'trans-3',
      tripId: 'trip-roma-amalfi-2026',
      type: 'auto_alquiler',
      title: 'Alquiler Fiat 500 Cabriolet Vintage',
      operator: 'Hertz Firenze Borgo Ognissanti',
      bookingReference: 'HZ-ITALIA-4401',
      departurePlace: 'Florencia Centro',
      arrivalPlace: 'Florencia Centro (Devolución)',
      departureDateTime: '2026-10-20T09:00:00',
      arrivalDateTime: '2026-10-22T19:00:00',
      notes: 'Seguro todo riesgo sin franquicia. Conductor principal: Lucas. Carnet internacional requerido',
      status: 'reservado',
      directLinkOrTicket: 'https://www.hertz.com',
    },
    {
      id: 'trans-4',
      tripId: 'trip-roma-amalfi-2026',
      type: 'ferry',
      title: 'Ferry Rápido Salerno -> Positano',
      operator: 'Travelmar Ferry',
      bookingReference: 'TM-78821',
      departurePlace: 'Molo Manfredi (Salerno)',
      arrivalPlace: 'Molo di Positano',
      departureDateTime: '2026-10-23T13:40:00',
      arrivalDateTime: '2026-10-23T14:50:00',
      notes: 'Disfrutar las vistas panorámicas desde la cubierta exterior superior',
      status: 'confirmado',
    },
    {
      id: 'trans-5',
      tripId: 'trip-roma-amalfi-2026',
      type: 'vuelo',
      title: 'Vuelo de Regreso Roma FCO -> Madrid (MAD)',
      operator: 'Iberia Express (IB3219)',
      bookingReference: 'IB-994KLA',
      departurePlace: 'Roma Fiumicino T3',
      arrivalPlace: 'Madrid Barajas T4',
      departureDateTime: '2026-10-28T18:20:00',
      arrivalDateTime: '2026-10-28T21:00:00',
      flightNumber: 'IB 3219',
      terminal: 'T3',
      seatPartner1: '15D (Pasillo)',
      seatPartner2: '15E (Medio)',
      status: 'confirmado',
    },
  ],
  accommodations: [
    {
      id: 'acc-1',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-roma',
      name: 'Residenza San Calisto - Trastevere',
      address: 'Via dell’Arco di San Calisto 20, Trastevere, Roma',
      checkInDate: '2026-10-15',
      checkInTime: '14:00',
      checkOutDate: '2026-10-19',
      checkOutTime: '11:00',
      bookingCode: 'BOOKING-982173',
      contactPhone: '+39 06 5833 1893',
      totalCost: 620,
      currency: 'EUR',
      status: 'pagado',
      googleMapsUrl: 'https://www.google.com/maps/search/Residenza+San+Calisto+Roma',
      roomType: 'Habitación Romántica Deluxe con balcón a patio de piedra',
      notes: 'Desayuno buffet incluido. Código de puerta de noche: 4920#',
    },
    {
      id: 'acc-2',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-florencia',
      name: 'Palazzo Guadagni Hotel Histórico',
      address: 'Piazza Santo Spirito 9, Oltrarno, Florencia',
      checkInDate: '2026-10-19',
      checkInTime: '15:00',
      checkOutDate: '2026-10-23',
      checkOutTime: '11:00',
      bookingCode: 'PG-FLO-4410',
      contactPhone: '+39 055 2658300',
      totalCost: 740,
      currency: 'EUR',
      status: 'reservado',
      googleMapsUrl: 'https://www.google.com/maps/search/Palazzo+Guadagni+Hotel+Firenze',
      roomType: 'Junior Suite con vista a la Basílica de Santo Spirito',
      notes: 'Loggia en el piso superior para ver el atardecer con Spritz',
    },
    {
      id: 'acc-3',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-costa-amalfitana',
      name: 'Hotel Villa Franca Positano',
      address: 'Viale Pasitea 318, 84017 Positano SA',
      checkInDate: '2026-10-23',
      checkInTime: '15:00',
      checkOutDate: '2026-10-28',
      checkOutTime: '12:00',
      bookingCode: 'VFRANCA-2026-LUCSOF',
      contactPhone: '+39 089 875655',
      totalCost: 1450,
      currency: 'EUR',
      status: 'pendiente',
      googleMapsUrl: 'https://www.google.com/maps/search/Hotel+Villa+Franca+Positano',
      roomType: 'Sea View Suite con terraza privada y jacuzzi',
      notes: 'Piscina infinity climatizada en el techo con vista 360° al golfo',
    },
  ],
  sites: [
    {
      id: 'site-1',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-roma',
      name: 'Fontana di Trevi al Amanecer',
      category: 'romantico',
      googleMapsUrl: 'https://www.google.com/maps/search/Fontana+di+Trevi+Roma',
      address: 'Piazza di Trevi, 00187 Roma RM, Italia',
      photos: [
        'https://images.unsplash.com/photo-1525874684015-58379d421a52?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Ir a las 07:15hs para tirar la moneda juntos sin multitudes y sacar fotos mágicas con luz dorada.',
      openingHours: 'Abierto 24 horas (Gratis)',
      estimatedCost: '0 € (Solo la moneda)',
      status: 'favorito',
      recommendedBy: 'p2',
      tags: ['Amanecer', 'Fotos', 'Imperdible', 'Romántico'],
      rating: 5,
    },
    {
      id: 'site-2',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-roma',
      name: 'Osteria da Fortunata (Trastevere / Campo de Fiori)',
      category: 'restaurante',
      googleMapsUrl: 'https://www.google.com/maps/search/Osteria+da+Fortunata+Roma',
      address: 'Via del Pellegrino 11/12, 00186 Roma RM',
      photos: [
        'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Las nonnas hacen la pasta a mano en la vidriera. Pedir los Strozzapreti a la Carbonara y Tagliolini al Ragu.',
      openingHours: '12:00 - 00:00 hs',
      estimatedCost: '35 - 45 € por pareja',
      status: 'por_visitar',
      recommendedBy: 'p1',
      tags: ['Pasta Fresca', 'Auténtico', 'Carbonara'],
      rating: 5,
    },
    {
      id: 'site-3',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-florencia',
      name: 'Mirador Piazzale Michelangelo al Atardecer',
      category: 'mirador',
      googleMapsUrl: 'https://www.google.com/maps/search/Piazzale+Michelangelo+Firenze',
      address: 'Piazzale Michelangelo, 50125 Firenze FI',
      photos: [
        'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Comprar una botella de vino Chianti y sentarse en las escaleras a escuchar músicos callejeros viendo el Ponte Vecchio encenderse.',
      openingHours: 'Siempre abierto (Gratuito)',
      estimatedCost: '15 € (Vino y quesos)',
      status: 'favorito',
      recommendedBy: 'both',
      tags: ['Atardecer', 'Vista Panorámica', 'Música en vivo'],
      rating: 5,
    },
    {
      id: 'site-4',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-costa-amalfitana',
      name: 'Paseo en Barco Privado por Capri y Faraglioni',
      category: 'aventura',
      googleMapsUrl: 'https://www.google.com/maps/search/Positano+Capri+Boat+Tour',
      address: 'Muelle de Positano',
      photos: [
        'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Cruzar el arco de los Faraglioni donde según la tradición hay que darse un beso para tener amor eterno.',
      openingHours: 'Salida 10:00 - Regreso 17:00 hs',
      estimatedCost: '180 € por persona con prosecco incluido',
      status: 'por_visitar',
      recommendedBy: 'p1',
      tags: ['Capri', 'Navegación', 'Beso Eterno', 'Snorkel'],
      rating: 5,
    },
    {
      id: 'site-5',
      tripId: 'trip-roma-amalfi-2026',
      cityId: 'city-costa-amalfitana',
      name: 'Ristorante Rada Beach & Club Positano',
      category: 'romantico',
      googleMapsUrl: 'https://www.google.com/maps/search/Rada+Restaurant+Positano',
      address: 'Via G. Marconi 1, Spiaggia Grande, Positano',
      photos: [
        'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      ],
      notes: 'Mesa en primera línea de playa con velas y sonido de las olas. Reserva confirmada para nuestra última noche.',
      openingHours: '20:00 - 23:30 hs',
      estimatedCost: '110 € por persona',
      status: 'favorito',
      recommendedBy: 'p2',
      tags: ['Cena Romántica', 'Frente al Mar', 'Alta Cocina'],
      rating: 5,
    },
  ],
  packingList: [
    // Lucas
    {
      id: 'pack-1',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Camisas de lino frescas (4)',
      category: 'ropa',
      assignedTo: 'p1',
      isPacked: true,
      quantity: 4,
      notes: 'Blancas y celestes para fotos en Positano',
    },
    {
      id: 'pack-2',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Zapatillas de trekking urbano cómodas',
      category: 'calzado',
      assignedTo: 'p1',
      isPacked: true,
      quantity: 1,
      notes: 'Para los adoquines de Roma',
    },
    {
      id: 'pack-3',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Traje de baño y toalla de microfibra',
      category: 'playa_montana',
      assignedTo: 'p1',
      isPacked: false,
      quantity: 2,
    },
    {
      id: 'pack-4',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Cámara Mirrorless Sony + 2 baterías extra',
      category: 'tecnologia',
      assignedTo: 'p1',
      isPacked: true,
      quantity: 1,
      notes: 'Llevar tarjeta SD de 256GB limpia',
    },
    // Sofía
    {
      id: 'pack-5',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Vestidos largos de verano / otoñales',
      category: 'ropa',
      assignedTo: 'p2',
      isPacked: true,
      quantity: 5,
      notes: 'Amarillo para Capri y blanco para Roma',
    },
    {
      id: 'pack-6',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Sandalias de cuero bajas + Zapatillas blancas',
      category: 'calzado',
      assignedTo: 'p2',
      isPacked: false,
      quantity: 2,
    },
    {
      id: 'pack-7',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Protector solar facial FPS 50 + Skincare',
      category: 'higiene',
      assignedTo: 'p2',
      isPacked: true,
      quantity: 1,
    },
    {
      id: 'pack-8',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Sombrero de paja y pañuelo para la iglesia',
      category: 'ropa',
      assignedTo: 'p2',
      isPacked: false,
      quantity: 2,
      notes: 'Obligatorio para hombros en Vaticano',
    },
    // Compartido
    {
      id: 'pack-9',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Adaptador universal de enchufes y zapatilla USB múltiple',
      category: 'tecnologia',
      assignedTo: 'compartido',
      isPacked: true,
      quantity: 1,
      notes: 'Para cargar los 2 móviles y la cámara juntos',
    },
    {
      id: 'pack-10',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Botiquín de viaje (Ibuprofeno, curitas, pastillas de mareo ferry)',
      category: 'botiquin',
      assignedTo: 'compartido',
      isPacked: true,
      quantity: 1,
      notes: 'Dramamine para el barco en Amalfi',
    },
    {
      id: 'pack-11',
      tripId: 'trip-roma-amalfi-2026',
      name: 'Powerbank de 20.000 mAh de carga rápida',
      category: 'tecnologia',
      assignedTo: 'compartido',
      isPacked: false,
      quantity: 1,
      notes: 'Llevar siempre en equipaje de mano (prohibido en bodega)',
    },
  ],
  documents: [
    {
      id: 'doc-1',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Pasaporte Vigente de Lucas',
      type: 'pasaporte',
      owner: 'p1',
      status: 'listo',
      expirationDate: '2030-04-12',
      notes: 'Válido por más de 3 años',
    },
    {
      id: 'doc-2',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Pasaporte Vigente de Sofía',
      type: 'pasaporte',
      owner: 'p2',
      status: 'listo',
      expirationDate: '2028-11-20',
      notes: 'Renovado recientemente, perfecto estado',
    },
    {
      id: 'doc-3',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Seguro Médico Internacional Assist Card (Cobertura 150.000€)',
      type: 'seguro',
      owner: 'ambos',
      status: 'listo',
      expirationDate: '2026-10-30',
      notes: 'Póliza #AC-994821. Teléfono de asistencia 24h: +34 91 123 4567',
    },
    {
      id: 'doc-4',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Permiso Internacional de Conducir (Automóvil Club)',
      type: 'licencia',
      owner: 'p1',
      status: 'en_tramite',
      expirationDate: '2027-09-01',
      reminderDate: '2026-09-15',
      notes: 'Retirar el certificado en la sede central antes de fin de mes',
    },
    {
      id: 'doc-5',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Vouchers y Entradas Vaticano + Coliseo descargadas offline',
      type: 'voucher_hotel',
      owner: 'ambos',
      status: 'listo',
      notes: 'Guardados en PDF en el móvil y en la app',
    },
  ],
  tasks: [
    {
      id: 'task-1',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Avisar al banco para habilitar tarjetas en Europa y compras en el exterior',
      assignedTo: 'ambos',
      dueDate: '2026-10-10',
      priority: 'alta',
      completed: false,
      notes: 'Verificar límites diarios en cajeros automáticos',
    },
    {
      id: 'task-2',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Contratar eSIM de datos móviles ilimitados (Holafly / Airalo)',
      assignedTo: 'p1',
      dueDate: '2026-10-12',
      priority: 'alta',
      completed: true,
      notes: 'Instalar el perfil QR pero activar al aterrizar',
    },
    {
      id: 'task-3',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Comprar candados TSA para las maletas',
      assignedTo: 'p2',
      dueDate: '2026-10-05',
      priority: 'media',
      completed: true,
    },
    {
      id: 'task-4',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Dejar llaves y comida a la vecina para cuidar las plantas y a Milo',
      assignedTo: 'ambos',
      dueDate: '2026-10-14',
      priority: 'alta',
      completed: false,
    },
    {
      id: 'task-5',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Descargar mapas offline en Google Maps de Roma, Florencia y Positano',
      assignedTo: 'p1',
      dueDate: '2026-10-13',
      priority: 'media',
      completed: false,
    },
  ],
  messages: [
    {
      id: 'msg-1',
      tripId: 'trip-roma-amalfi-2026',
      fromPartnerId: 'p1',
      toPartnerId: 'p2',
      message: '¡No puedo creer que en pocas semanas vamos a estar comiendo gelato frente al Coliseo! Te amo y preparé una sorpresita para el atardecer en Positano ❤️',
      moodEmoji: '💖',
      timestamp: '2026-08-28T18:45:00.000Z',
      isSurprise: false,
      isRead: true,
    },
    {
      id: 'msg-2',
      tripId: 'trip-roma-amalfi-2026',
      fromPartnerId: 'p2',
      toPartnerId: 'p1',
      message: '¡Sos el mejor compañero de viaje del mundo! Ya tengo armada la playlist para la ruta en el Fiat 500 por la Toscana 🚗🎶 ¡Contando los días!',
      moodEmoji: '✨',
      timestamp: '2026-08-29T10:15:00.000Z',
      isSurprise: false,
      isRead: true,
    },
    {
      id: 'msg-3',
      tripId: 'trip-roma-amalfi-2026',
      fromPartnerId: 'p1',
      toPartnerId: 'p2',
      message: '💌 Carta Especial de Aniversario: Abrir únicamente cuando estemos navegando los Faraglioni de Capri...',
      moodEmoji: '🍾',
      timestamp: '2026-08-30T01:20:00.000Z',
      isSurprise: true,
      revealAt: '2026-10-24T12:00:00',
      isRead: false,
    },
  ],
  gallery: [
    {
      id: 'gal-1',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Nuestros pasajes en mano y brindis por el viaje!',
      mediaUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=80',
      mediaType: 'image',
      date: '2026-08-15',
      uploadedById: 'p1',
      hearts: ['p1', 'p2'],
      caption: 'Brindando con un vinito el día que compramos los pasajes a Italia 🥂',
    },
    {
      id: 'gal-2',
      tripId: 'trip-roma-amalfi-2026',
      title: 'La vista soñada de Positano que nos espera',
      mediaUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=900&q=80',
      mediaType: 'image',
      date: '2026-08-20',
      cityId: 'city-costa-amalfitana',
      uploadedById: 'p2',
      hearts: ['p1', 'p2'],
      caption: 'Guardé esta postal para recordarnos por qué trabajamos tanto este año 🌅',
    },
    {
      id: 'gal-3',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Vino y pasta fresca en Roma',
      mediaUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80',
      mediaType: 'image',
      date: '2026-08-22',
      cityId: 'city-roma',
      uploadedById: 'p1',
      hearts: ['p2'],
      caption: 'El primer plato de pasta que vamos a pedir en Trastevere 🍝',
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Permiso Internacional de Conducir',
      body: 'Recordatorio: Retirar el carnet internacional antes del 15 de Septiembre para el auto en Toscana.',
      type: 'document',
      timestamp: '2026-08-29T12:00:00.000Z',
      read: false,
      targetTab: 'equipaje-docs',
    },
    {
      id: 'notif-2',
      tripId: 'trip-roma-amalfi-2026',
      title: '¡Mensaje nuevo en el Buzón!',
      body: 'Lucas te dejó una carta sorpresa con candado para el viaje.',
      type: 'mailbox',
      timestamp: '2026-08-30T01:20:00.000Z',
      read: false,
      targetTab: 'buzon',
    },
    {
      id: 'notif-3',
      tripId: 'trip-roma-amalfi-2026',
      title: 'Pago pendiente de Alojamiento en Positano',
      body: 'Recordá que la reserva de Hotel Villa Franca se abonará en destino.',
      type: 'payment',
      timestamp: '2026-08-28T09:00:00.000Z',
      read: true,
      targetTab: 'gastos',
    },
  ],
};
